on:
  push:
    branches:
    - main
jobs:
  deploy_gh_pages:
    name: Publish page automatically
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Deploy
      run: npm run deploy
